### ISSUE TITLE
Add 'Time & Date' events to occur if turned on in the menu.

### ISSUE THREAD

**Issue by DivineJayce** [DivinElegy/GrooveNights#14]
[To happen on all screens except Gameplay unless mentioned otherwise]

Using a player's Weight on their card we can let them set their birthdate (ie 1210 = December 10th), will require some trickery to determine where the month and day cut off since 0111 would become 111 as an integer (which could mean Jan 11th becomes Nov 1st), simple case is to see how many digits there are, if 4 then the first 2 are the month. If 3 then the first digit only is the month.

ANYWAY for birthdays it would be similar to the snow effect except there would be confetti and streamers and shit.

April 20th will turn everything on rainbow and wag with the transition arrow being replaced with a weed leaf.

July 4th could recolour the theme to Blue Frames with Red Backgrounds (and white text to make the colours of the US Flag), the Transition Arrow can be replaced by a bald eagle, etc.

Playing on Christmas Day triggers snowfall and a recolour to Red Frames and Green Background or something.

New Years could just do a one-off explosion of confetti and cheering sounds regardless of what screen you're on and no matter whether you're playing a song, it'll have to do a check of the system time and maybe have an onscreen countdown from the 10sec mark.

**Comment by ghost** [comment]
I'll try work something in to EasterEggs.lua to make this happen.
