### ISSUE TITLE
Game crashes after selecting singleplayer in dance mode

### ISSUE THREAD

**Issue by MerelFloofs** [DivinElegy/GrooveNights#49]
[crashinfo-1461410163.txt](https://github.com/DivinElegy/GrooveNights/files/232932/crashinfo-1461410163.txt)

**Comment by ghost** [comment]
Sorry, this is most likely a bug with StepMania, not the theme. That error is related to memory allocation problems on Windows.

**Comment by MerelFloofs** [comment]
@cameron1729 I upgraded opening to the newest patch avalible on the site. I got the theme to work up until the same point as last time. Here is a log and crash report of the session. Also, I am using wine on Linux if that makes a difference. 
[log.txt](https://github.com/DivinElegy/GrooveNights/files/233079/log.txt)
[crashinfo-1461431945.txt](https://github.com/DivinElegy/GrooveNights/files/233080/crashinfo-1461431945.txt)

**Comment by ghost** [comment]
OpenITG actually works better on Linux. You can get binaries [here](http://openitg.gr-p.com/) or get the [source from GitHub](https://github.com/openitg/openitg) and compile it. You'll definitely have a better time running it on Linux than on Windows.

**Comment by MerelFloofs** [comment]
@cameron1729 does it require any dependencies? It won't run for me for some reason.

**Comment by ghost** [comment]
The best advice I can give is to try running it from a terminal with `./openitg-beta-2` or whatever one you picked and check the error messages (please don't post the error messages here, you'll need to google them to work out what to do).

**Comment by MerelFloofs** [comment]
@cameron1729 Ok, thanks!
